declare module 'lucide-react' {
  import type { FC, SVGProps } from 'react';

  type IconProps = SVGProps<SVGSVGElement> & {
    size?: string | number;
    absoluteStrokeWidth?: boolean;
  };

  export const AlertCircle: FC<IconProps>;
  export const Calendar: FC<IconProps>;
  export const Music: FC<IconProps>;
  export const Users: FC<IconProps>;
  export const ListMusic: FC<IconProps>;
  export const Edit2: FC<IconProps>;
  export const Trash2: FC<IconProps>;
  export const Plus: FC<IconProps>;
  export const Save: FC<IconProps>;
  export const X: FC<IconProps>;
  export const Settings: FC<IconProps>;
  export const Home: FC<IconProps>;
  export const Bell: FC<IconProps>;
  export const LogOut: FC<IconProps>;
  export const ChevronRight: FC<IconProps>;
  export const Menu: FC<IconProps>;
  export const Search: FC<IconProps>;
  export const Filter: FC<IconProps>;
  export const Eye: FC<IconProps>;
  export const EyeOff: FC<IconProps>;
  export const TrendingUp: FC<IconProps>;
  export const Heart: FC<IconProps>;
  export const MessageSquare: FC<IconProps>;
  export const MoreVertical: FC<IconProps>;
  export const Check: FC<IconProps>;
  export const CheckCircle: FC<IconProps>;
  export const ChevronDown: FC<IconProps>;
  export const ChevronUp: FC<IconProps>;
  export const Circle: FC<IconProps>;
  export const AlertTriangle: FC<IconProps>;
  export const Info: FC<IconProps>;
  export const Loader: FC<IconProps>;
  export const Upload: FC<IconProps>;
  export const Download: FC<IconProps>;
  export const Share2: FC<IconProps>;
  export const Copy: FC<IconProps>;
  export const Mail: FC<IconProps>;
  export const Phone: FC<IconProps>;
  export const MapPin: FC<IconProps>;
  export const Globe: FC<IconProps>;
  export const Zap: FC<IconProps>;
  export const BookOpen: FC<IconProps>;
  export const Inbox: FC<IconProps>;
  export const HelpCircle: FC<IconProps>;
  export const BarChart3: FC<IconProps>;
  export const ArrowRight: FC<IconProps>;
  export const DollarSign: FC<IconProps>;
  export const CreditCard: FC<IconProps>;
  export const TrendingDown: FC<IconProps>;
  export const Percent: FC<IconProps>;
  export const Clock: FC<IconProps>;
  export const Clock1: FC<IconProps>;
  export const LayoutDashboard: FC<IconProps>;
  export const Shield: FC<IconProps>;
  export const ChevronLeft: FC<IconProps>;
  export const Building: FC<IconProps>;
  export const Lock: FC<IconProps>;
  export const Monitor: FC<IconProps>;
  export const Play: FC<IconProps>;
  export const Star: FC<IconProps>;
  export const Sparkles: FC<IconProps>;
  export const Video: FC<IconProps>;
  export const Wallet: FC<IconProps>;
  export const Church: FC<IconProps>;
  export const Cross: FC<IconProps>;
  export const Smartphone: FC<IconProps>;
  export const ArrowLeft: FC<IconProps>;
  export const Send: FC<IconProps>;
  export const Cell: FC<IconProps>;
  export const UsersRound: FC<IconProps>;
  export const GraduationCap: FC<IconProps>;
  // Add more icons as needed
}
